from decouple import config

# OPEN WEATHER
OPENWEATHER_API_KEY = config('OPENWEATHER_API_KEY')

# SPOTIFY
SPOTIFY_CLIENT_ID = config('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = config('SPOTIFY_CLIENT_SECRET')
